
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:  <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: sartori_store_development

test:
  <<: *default
  database: sartori_store_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
